// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191111133354_InicialMigration")]
    partial class InicialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Estudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BpmInicial");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.Property<int>("Dificuldade");

                    b.Property<int>("Fluencia");

                    b.Property<int>("Minutos");

                    b.Property<string>("Origem");

                    b.Property<DateTime>("PrimeiroTreino");

                    b.Property<int>("Proposito");

                    b.Property<string>("Tecnica");

                    b.Property<int>("TempoPraticado");

                    b.Property<string>("Titulo");

                    b.Property<DateTime>("UltimoTreino");

                    b.Property<int>("VezesPraticado");

                    b.HasKey("Id");

                    b.ToTable("Estudos");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Idade");

                    b.Property<string>("Nome");

                    b.Property<string>("Sobrenome");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Idade = 52,
                            Nome = "João",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 2,
                            Idade = 22,
                            Nome = "Maria",
                            Sobrenome = "Hoffman"
                        },
                        new
                        {
                            Id = 3,
                            Idade = 23,
                            Nome = "Pedro",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 4,
                            Idade = 32,
                            Nome = "José",
                            Sobrenome = "Correa"
                        },
                        new
                        {
                            Id = 5,
                            Idade = 14,
                            Nome = "Akira",
                            Sobrenome = "Duarte"
                        },
                        new
                        {
                            Id = 6,
                            Idade = 21,
                            Nome = "Brunna",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 7,
                            Idade = 26,
                            Nome = "Natália",
                            Sobrenome = "Pirassununga"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
