// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200127195324_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Domain.Estudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BpmInicial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fluencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrimeiroTreino")
                        .HasColumnType("TEXT");

                    b.Property<int>("Proposito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tecnica")
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoPraticado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimoTreino")
                        .HasColumnType("TEXT");

                    b.Property<int>("VezesPraticado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Estudos");
                });

            modelBuilder.Entity("Domain.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Idade = 52,
                            Nome = "João",
                            Sobrenome = "Silva"
                        },
                        new
                        {
                            Id = 2,
                            Idade = 22,
                            Nome = "Maria",
                            Sobrenome = "Hoffman"
                        },
                        new
                        {
                            Id = 3,
                            Idade = 23,
                            Nome = "Pedro",
                            Sobrenome = "Souza"
                        },
                        new
                        {
                            Id = 4,
                            Idade = 32,
                            Nome = "José",
                            Sobrenome = "Correa"
                        },
                        new
                        {
                            Id = 5,
                            Idade = 14,
                            Nome = "Akira",
                            Sobrenome = "Duarte"
                        },
                        new
                        {
                            Id = 6,
                            Idade = 21,
                            Nome = "Brunna",
                            Sobrenome = "Pereira"
                        },
                        new
                        {
                            Id = 7,
                            Idade = 26,
                            Nome = "Natália",
                            Sobrenome = "Pirassununga"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
